Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2024
Var
a,b,s:inteiro

Inicio
escreval("Digite dois números: ")
leia(a,b)
s <- a+b
escreval("A média da soma de seus dois números é:",s*(45/100))


Fimalgoritmo