Algoritmo "semnome"

Var
n1, n2, n3, n4, n5, total:real


Inicio

      escreval("primeiro número")
      leia(n1)
      escreval("segundo número")
      leia(n2)
      escreval("terceiro número")
      leia(n3)
      escreval("quarto número")
      leia(n4)
      escreval("quinto número")
      leia(n5)
      total<- n1 + n2 + n3 + n4 + n5
      escreva("O resultado é ", total)

Fimalgoritmo